"""Add hour payment

Revision ID: 51d4f6c1a900
Revises: 0da74c22e0c2
Create Date: 2023-08-06 18:26:01.389826

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = '51d4f6c1a900'
down_revision = '0da74c22e0c2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('hour_payment', sa.Integer()))
    op.alter_column('notes', 'text', server_default='')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'hour_payment')
    # ### end Alembic commands ###
