"""not-nullable user_id fk

Revision ID: 776949c53d43
Revises: 93c569a967b6
Create Date: 2023-07-27 01:39:56.225221

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '776949c53d43'
down_revision = '93c569a967b6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_notes_user_id_users', 'notes', type_='foreignkey')
    op.create_foreign_key(op.f('fk_notes_user_id_users'), 'notes', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_notes_user_id_users'), 'notes', type_='foreignkey')
    op.create_foreign_key('fk_notes_user_id_users', 'notes', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
