"""Add password

Revision ID: 823c240c0345
Revises: 51d4f6c1a900
Create Date: 2023-08-09 04:16:18.864425

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '823c240c0345'
down_revision = '51d4f6c1a900'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password')
    # ### end Alembic commands ###
